version: "3"
services:
  counter:
    image: ghcr.io/aitorastorga/aichan-visit-counter:latest
    ports:
      - "8000:8000"
    environment:
      ROCKET_ADDRESS: "0.0.0.0"
      ROCKET_PORT: "8000"
      API_KEY: "your_secret_api_key_here"
